### PR TITLE
249-Fix `Delete` Bug

### LINKED ISSUE #249: Fix `Delete` bug
Fix bug in `delete command` where user will not be able to `delete Candidate` due to implementation of `FocusCard`

### PR DESCRIPTION
**Pull request by tiewweijian**
closes #249

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -48,7 +48,7 @@ public CommandResult execute(Model model) throws CommandException {
         model.deleteCandidate(candidateToDelete);
 
         return new CommandResult(String.format(MESSAGE_DELETE_CANDIDATE_SUCCESS, candidateToDelete), false,
-                false, true, -1, true, targetIndex.getZeroBased());
+                false, false, -1, true, targetIndex.getZeroBased());
```
Comment (charmainehly) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:51]: ello, just wanted to make a quick check as I'm a little unsure of what behaviour is impacted by the change of this from true to false?

Comment (tiewweijian) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java:51]: For this `boolean`, the argument is mainly used for the `FocusCommand`.  As for refreshing the `FocusCard`, it is further implemented in the `MainWindow` class and won't depend on this variable. 

I changed it to false to prevent any rouge `FocusCommand` from starting up (and will cause more exceptions)

Comment (charmainehly) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java:51]: ah yep, that makes sense, got it, thank you!!

**Review by charmainehly — APPROVED** [review]
LGTM! thanks for fixing the bug and addressing my qns!!! :-)

**Review by domlimm — APPROVED** [review]
Same query as Charmaine that's all! Thanks for fixing this WJ! LGTM!
