### PR TITLE
Fix implementation of find command for candidate field

### LINKED ISSUE #189: Fix bug on candidate search under `find` command
Currently the `find` command for the `candidate` field is implemented by checking the `toString()` of each Candidate.

Introduces a bug where keywords like `availability` is included in the search.

To create a new method that searches through each of the candidates' fields instead.

### PR DESCRIPTION
**Pull request by charmainehly**
Currently, the find command searches for all fields under each candidate via the candidate.toString() method.

This causes the search to include irrelevant strings e.g."availability" and "phone". This also results in edge cases
where find k/availability f/candidate will bring up positive search results.

Let's fix the implementation in the CandidateContainsKeywordsPredicate class so that the find command will separately check through each of the candidate's fields and return through if any of these fields include any of the keywords.

Note: Small edit to Seniority class and predicate class to enable the find command to search according to the text that
the candidate card in the gui displays, i.e. COM1, COM2 etc.

Closes #189

### CODE REVIEW

**Review by LeeEnEn — APPROVED** [review]
LGTM! Shall wait for Dom to review and merge.

File: src/main/java/seedu/address/model/candidate/Seniority.java [hunk 1]
```diff
@@ -4,7 +4,7 @@
 
 /**
  * Represents a Candidate's seniority in TAlent Assistant™.
- * Guarantees: immutable; is valid as declared in {@link #isValidSeniority(int)}
+ * Guarantees: immutable; is valid as declared in {@link #isValidSeniority(String)}
```
Comment (domlimm) [inline src/main/java/seedu/address/model/candidate/Seniority.java:7]: Whoops! Nice catch @charmainehly! 😄

File: src/main/java/seedu/address/model/candidate/Seniority.java [hunk 2]
```diff
@@ -33,6 +33,10 @@ public static boolean isValidSeniority(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
+    public String toSearchString() {
+        return "COM" + seniority;
```
Comment (domlimm) [inline src/main/java/seedu/address/model/candidate/Seniority.java:37]: @charmainehly char, you could possibly use Line 12's string constant.
```suggestion
        return COM_VALUE + seniority;
```

File: src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java [hunk 3]
```diff
@@ -40,12 +40,19 @@ public boolean test(Candidate candidate) {
...
+        return keywords.stream().anyMatch(keyword ->
+                StringUtil.containsStringIgnoreCase(candidate.getApplicationStatus().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getCourse().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getEmail().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getInterviewStatus().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getName().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getPhone().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getSeniority().toSearchString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(candidate.getStudentId().toString(), keyword)
+                        || StringUtil.containsStringIgnoreCase(sb.toString(), keyword));
```
Comment (domlimm) [inline src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java:55]: Love this. Nice job!

Also, `StringUtil.containsStringIgnore` seem to be better than `String.equalsIgnoreCase(...)` 🤔 It's neater! Nice!

**Review by domlimm — CHANGES_REQUESTED** [review]
Yahoo! All LGTM! Could make that tiny change, and I'll approve and merge. Thanks @charmainehly! Nice job! 😄

File: src/main/java/seedu/address/model/candidate/Seniority.java [hunk 4]
```diff
@@ -34,7 +34,7 @@ public static boolean isValidSeniority(String test) {
     }
 
     public String toSearchString() {
-        return "COM" + seniority;
+        return COM_VALUE + seniority;
```
Comment (domlimm) [inline src/main/java/seedu/address/model/candidate/Seniority.java:37]: Cheers char! 😄

**Review by domlimm — APPROVED** [review]
LGTM! Merging now! 💯
